# We want to spawn several separate services from Docker images and manage all
# of them from this file.
services:

  ##############################################################################
  #
  # Proxy
  #   We use Nginx as a reverse proxy to direct requests to the ports of the
  #   correct services. This way we can hide the application's inner network.
  #
  ##############################################################################
  proxy:
    container_name: shuffle.proxy.development

    # We can use volumes to copy our reverse proxy configuration into Nginx.
    volumes:
      # Use the development configuration to expose only what's necessary.
      - ./proxy/development.conf:/etc/nginx/nginx.conf
      - ./proxy/logs:/etc/nginx/error_log.log

  ##############################################################################
  #
  # Client
  #   This is the service that serves all client-side files.
  #
  ##############################################################################
  client:
    container_name: shuffle.client.development

    # We want to build from the development dockerfile in the client directory.
    build:
      context: ./client/
      dockerfile: development.dockerfile

    # We want to bind the changes inside the container to a local folder so that
    # we can update the code in real time.
    volumes:
      - ./client:/client

  ##############################################################################
  #
  # API
  #   This is the service that serves all server-side requests.
  #
  ##############################################################################
  api:
    container_name: shuffle.api.development

    # We want to build from the development dockerfile in the API directory.
    build:
      context: ./api/
      dockerfile: development.dockerfile

    # We want to bind the changes inside the container to a local folder so that
    # we can update the code in real time.
    volumes:
      - ./api:/api
